services:
  fdp-ui:
    image: "fairdata/fairdatapoint-ui:${FDP_UI_VERSION:-latest}"  # todo: pin default when we've reached a stable version
    restart: no
    ports:
      # the fdp-ui docker.nginx.conf configures nginx in the fdp-ui container to listen on port 8080
      # we expose fdp-ui on localhost at port 81, because port 80 is already occupied by fdp-client
      # todo: change to port 80 once fdp-client is removed
      - "127.0.0.1:81:8080"
    volumes:
      # override the default runtime config to point to the fdp api on localhost
      - "./config.json:/usr/share/nginx/html/config.json"
    depends_on:
      fdp:
        condition: service_healthy
    healthcheck:
      test: wget --quiet --spider http://127.0.0.1:8080 || exit 1
      interval: 5m
      start_interval: 3s
      start_period: 30s
