# TODO: refactor for component re-use
name: fdp2m
services:
  postgres:
    image: "postgres:${POSTGRES_VERSION:-17.5}"
    restart: no
    healthcheck:
      test: pg_isready --dbname=fdp --username=fdp || exit 1
      start_interval: 3s
      start_period: 30s
    environment:
      POSTGRES_DB: fdp
      POSTGRES_PASSWORD: fdp
      POSTGRES_USER: fdp

  fdp:
    image: "fairdata/fairdatapoint:${FDP_VERSION:-2.0.0-alpha.2}"
    restart: no
    environment:
      INSTANCE_CLIENTURL: http://localhost
      INSTANCE_PERSISTENTURL: http://localhost
      JAVA_TOOL_OPTIONS: -Dspring.profiles.active=development
      SERVER_PORT: 8080
      SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      SPRING_DATASOURCE_PASSWORD: fdp
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fdp
      SPRING_DATASOURCE_USERNAME: fdp
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: wget -q --spider http://localhost:8080 || exit 1
      start_interval: 3s
      start_period: 30s

  fdp-client:
    image: "fairdata/fairdatapoint-client:${FDP_CLIENT_VERSION:-2.0.0-alpha.2}"
    restart: no
    ports:
      - "127.0.0.1:80:80"
    environment:
      FDP_HOST: fdp:8080
    depends_on:
      fdp:
        condition: service_healthy
