# note docker compose automatically loads compose.yml *and* compose.override.yml (if present)
services:
  fdp-client:
    depends_on: !reset []
    # when running the fdp from source, the fdp-client needs network access to the docker host.
    environment:
      FDP_HOST: host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
