# note docker compose automatically loads compose.yml *and* compose.override.yml (if present)
services:
  fdp:
    environment:
      PING_ENABLED: true
      PING_ENDPOINTS: http://fdp-index:8080

  fdp-index-client:
    # override the exposed port because fdp-client already is already using port 80
    ports: !override
      - "127.0.0.1:82:80"
