# note docker compose automatically loads compose.yml *and* compose.override.yml (if present)
services:
  fdp:
    environment:
      # the fdp-index tries to harvest the fdp via the client-url,
      # so we need to make this available to the fdp-index using the docker host-gateway
      # todo: this does not work... index says unreachable
      INSTANCE_CLIENTURL: http://host.docker.internal:8080
      INSTANCE_PERSISTENTURL: http://host.docker.internal:8080
      PING_ENABLED: true
      # the fdp can ping the fdp-index directly over the docker network
      PING_ENDPOINTS: http://fdp-index:8080

  fdp-index:
    # the fdp-index will try to harvest the fdp via its INSTANCE_CLIENT_URL,
    # which must be a "public" url, so we must give it access to the host-gateway
    extra_hosts:
      - "host.docker.internal:host-gateway"

  fdp-index-client:
    # override the exposed port because fdp-client already is already using port 80
    ports: !override
      - "127.0.0.1:82:80"
