# setup for local development, running fdp from source
name: fdppv1devfdp
include:
  - ../../../../components/db/graphdb/compose.yml
  - ../../../../components/db/mongo.yml
  - ../../../../components/v1/fdp-client.yml
