services:
  graphdb:
    image: "ontotext/graphdb:${GRAPHDB_VERSION:-10.8.8}"
    restart: no
    ports:
      # expose to localhost so we can use the graphdb web ui
      - "127.0.0.1:7200:7200"
    healthcheck:
      # test if reachable (also works if there are no repositories yet)
      test: "curl http://localhost:7200/rest/monitor/infrastructure --silent --fail || exit 1"
      start_interval: 3s
      start_period: 30s

  graphdb-init:
    # this service uses the graphdb rest api to create repositories defined in the repos/*.json files
    # (safe to call if repositories exist)
    # https://graphdb.ontotext.com/documentation/10.8/manage-repos-with-restapi.html#create-a-repository
    # https://graphdb.ontotext.com/documentation/10.8/manage-repos-with-curl.html
    image: "curlimages/curl:${CURL_VERSION:-latest}"
    restart: no
    volumes:
      - ".:/templates"
    environment:
      # space-separated list of repo names
      REPO_NAMES: fdp
    # the following curl request returns status 201 if the repo does not exist, or status 400 otherwise
    command:
      - sh
      - -c
      - |
        for name in $$REPO_NAMES
        do
        # substitute "repo-name" by variable name in graphdb repo template
        data=$$(sed s/repo-name/$$name/g /templates/graphdb-repo-template.json)
        # post repo definition to graphdb rest api
        curl http://graphdb:7200/rest/repositories --verbose --silent --header "Content-Type: application/json" --data "$$data"
        done
    depends_on:
      graphdb:
        condition: service_healthy
