# note docker compose automatically loads compose.yml *and* compose.override.yml (if present)
services:
  # configure fdp to use graphdb instead of the in-memory triple store
  fdp:
    environment:
      REPOSITORY_TYPE: 4
      REPOSITORY_GRAPHDB_URL: http://graphdb:7200
      REPOSITORY_GRAPHDB_REPOSITORY: fdp
    depends_on:
      # depend on graphdb (in addition to mongo)
      graphdb:
        condition: service_healthy
  # use docker managed volumes for data persistence
  graphdb:
    volumes:
      - graphdbdata:/opt/graphdb/home
  mongo:
    volumes:
      - mongodbdata:/data/db

volumes:
  graphdbdata:
  mongodbdata:
