name: fdppv1
include:
  - ../../components/db/graphdb/compose.yml
  - ../../components/db/mongo/compose.yml
  - ../../components/v1/fdp/compose.yml
  - ../../components/v1/fdp-client/compose.yml
  - ../../components/v1/fdp-ui/compose.yml
