services:
  fdp-index:
    image: "fairdata/fairdatapoint:${FDP_VERSION:-1.22.2}"
    restart: no
    ports:
      # expose on localhost, simulating a "public" url
      - "127.0.0.1:8080:8080"
    environment:
      FDP_MONGO_DB: 'fdp-index'
      INSTANCE_CLIENTURL: "http://localhost:${FDP_INDEX_PORT:-8082}"
      INSTANCE_INDEX: true
      INSTANCE_PERSISTENTURL: "http://localhost:${FDP_INDEX_PORT:-8082}"
      PING_ENABLED: false
      # as of v1.22.1 the default (production) profile requires an explicit JWT secret
      SECURITY_JWT_TOKEN_SECRETKEY: ${SECURITY_JWT_TOKEN_SECRETKEY:-dummy_secret_do_not_use_in_production}
      SERVER_PORT: "${FDP_INDEX_PORT:-8082}"
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: "wget -q --spider http://localhost:${FDP_INDEX_PORT:-8082} || exit 1"
      interval: 5m
      start_interval: 3s
      start_period: 30s
