services:
  fdp:
    image: "fairdata/fairdatapoint:${FDP_VERSION:-1.17}"
    restart: no
    environment:
      SERVER_PORT: 8080
      INSTANCE_CLIENTURL: http://localhost
      INSTANCE_PERSISTENTURL: http://localhost
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: wget -q --spider http://localhost:8080 || exit 1
      start_interval: 3s
      start_period: 30s
