services:
  fdp-index:
    image: "fairdata/fairdatapoint:${FDP_VERSION:-2.0.0-alpha.2}"
    restart: no
    environment:
      INSTANCE_CLIENTURL: "http://localhost:${FDP_INDEX_PORT:-8082}"
      INSTANCE_INDEX: true
      INSTANCE_PERSISTENTURL: "http://localhost:${FDP_INDEX_PORT:-8082}"
      JAVA_TOOL_OPTIONS: -Dspring.profiles.active=development
      PING_ENABLED: false
      SERVER_PORT: "${FDP_INDEX_PORT:-8082}"
      SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      SPRING_DATASOURCE_PASSWORD: fdp
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fdp_index
      SPRING_DATASOURCE_USERNAME: fdp
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "wget -q --spider http://localhost:${FDP_INDEX_PORT:-8082} || exit 1"
      start_interval: 3s
      start_period: 30s
