services:
  fdp:
    image: "fairdata/fairdatapoint:${FDP_VERSION:-2.0.0-alpha.2}"
    restart: no
    environment:
      INSTANCE_CLIENTURL: http://localhost
      INSTANCE_PERSISTENTURL: http://localhost
      # TODO: using the development profile is a temporary workaround for FDP #634
      JAVA_TOOL_OPTIONS: -Dspring.profiles.active=development
      SERVER_PORT: 8080
      SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      SPRING_DATASOURCE_PASSWORD: fdp
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fdp
      SPRING_DATASOURCE_USERNAME: fdp
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: wget -q --spider http://localhost:8080 || exit 1
      start_interval: 3s
      start_period: 30s
